spring.application.name=E-Banking-System



#Database Configuration

spring.datasource.url=jdbc:postgresql://localhost:5000/bankdatabase
#spring.datasource.url=jdbc:postgresql://localhost:5000/demo
spring.datasource.username=postgres
spring.datasource.password=nilesh#123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

#jwt configuration

SECRET_KEY=MzJieXRlc0tleVNlY3JldEtleVNlY3JldEtleVNlY3JldA==

EXPIRATION=1

#Mail service configuration

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sequelextreme@gmail.com
spring.mail.password=rgdtzchxdrvkytio
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true